name: na-hmvs-${basename:${dataset.root_dir}}
tag: ""
seed: 42

dataset:
  name: hmvs
  root_dir: /home/yidaw/Documents/datasets/Buildings
  pose_path: /home/yidaw/Documents/datasets/Buildings/Building/Tile_+002_+002_AT.bin
  pcd_path: /home/yidaw/Documents/datasets/Buildings/Building/building_interest.ply
  mesh_exported_path: false
  img_downscale: 2 # 4 # better with more than 1000 x 1000 resolution
  cam_downscale: 80 # 200 # if false, to rescale the cameras/pts positions automatically
  repose: true # false
  up_est_method: camera # z-axis # camera/ground/z-axis 
  center_est_method: point # camera/point
  n_test_traj_steps: 4
  apply_mask: false
  load_data_on_gpu: false
  max_imgs: 500

model:
  name: neus
  radius: 1.0
  num_samples_per_ray: 4096
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 2048
  cos_anneal_end: ${trainer.max_steps}
  learned_background: true
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    sdf2weight: hf_neus
    geometric_bias_remove: false # refer to D-NeuS
    grad_type: finite_difference
    isosurface:
      method: mc
      resolution: 768 # 1536
      chunk: 2097152 # 128**3
      threshold: 0.
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 8
      log2_hashmap_size: 22
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      start_level: 4
      start_step: 0
      update_steps: 2000 # Don't set it larger then 2000, otherwise smoothness will be harmed, refer to NeuS2
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
    finite_difference_eps: progressive
    max_imgs: ${dataset.max_imgs}
    use_appearance_embedding: false
    use_average_appearance_embedding: ture
    appearance_embedding_dim: 16
    use_distortion: false
    unwarp_rays: true
  texture:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
    max_imgs: ${dataset.max_imgs}
    use_appearance_embedding: true
    use_average_appearance_embedding: ture
    appearance_embedding_dim: 32
  # background model configurations
  num_samples_per_ray_bg: 256
  geometry_bg:
    name: volume-density
    radius: ${model.radius}
    feature_dim: 8
    density_activation: trunc_exp
    density_bias: -1
    isosurface: null
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
  texture_bg:
    name: volume-radiance
    input_feature_dim: ${model.geometry_bg.feature_dim}
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
    max_imgs: ${dataset.max_imgs}
    use_appearance_embedding: true
    use_average_appearance_embedding: ture
    appearance_embedding_dim: 32

system:
  name: neus-system
  loss:
    lambda_rgb_mse: 1. # 10.
    lambda_rgb_l1: 1.
    lambda_mask: 0.0
    lambda_eikonal: 0.1
    lambda_adaptive: 1e-6
    lambda_curvature: 5e-4 # topology warmup
    curvature_warmup_steps: ${model.geometry.xyz_encoding_config.update_steps}
    lambda_sparsity: 0.0
    sparsity_scale: 1.
    lambda_distortion: 1e-4
    lambda_distortion_bg: 0.0
    lambda_opaque: 1e-2
    lambda_entropy: 1e-4
    lambda_surface_bias: 0.0 # [2e3, 0.0, 0.1, 5e4] # refer to D-NeuS
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      geometry_bg:
        lr: 0.01
      texture_bg:
        lr: 0.01
      variance:
        lr: 0.001
  warmup_steps: 500
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.warmup_steps}
    schedulers:
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        args:
          start_factor: 0.01
          end_factor: 1.0
          total_iters: ${system.warmup_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.warmup_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  chunk_size: 2097152
  export_vertex_color: True

trainer:
  max_steps: 1e5 # 3e5 
  log_every_n_steps: 500
  num_sanity_val_steps: 0
  val_check_interval: 1e5
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
