name: neuralangelo-dtu-wmask-${basename:${dataset.root_dir}}
tag: ""
seed: 42

dataset:
  name: dtu
  root_dir: ./load/DTU-neus/dtu_scan63
  cameras_file: cameras_sphere.npz
  img_downscale: 1 # 2 # specify training image size by either img_wh or img_downscale
  n_test_traj_steps: 20 # 60
  apply_mask: true
  max_imgs: 400

model:
  name: neus
  radius: 1.0
  num_samples_per_ray: 1024
  train_num_rays: 512
  max_train_num_rays: 2048
  grid_prune: false # it seems to be not helpful for scenes with masks, e.g. dtu
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 2048
  cos_anneal_end: 1e5
  learned_background: false
  background_color: white
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    grad_type: finite_difference
    finite_difference_eps: progressive
    sdf2weight: neus
    isosurface:
      method: mc
      resolution: 768
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 8
      log2_hashmap_size: 22
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      start_level: 4
      start_step: 0
      update_steps: 2000
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
    use_distortion: false
    unwarp_rays: true
  texture:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
    max_imgs: ${dataset.max_imgs}
    use_appearance_embedding: false
    use_average_appearance_embedding: ture
    appearance_embedding_dim: 32

system:
  name: neus-system
  loss:
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 1.
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_curvature: 1e-4 # 1e-4 # topology warmup
    curvature_warmup_steps: 5000
    lambda_sparsity: 0.0
    lambda_distortion: 0.0
    lambda_distortion_bg: 0.0
    lambda_opaque: 0.0
    lambda_entropy: 0.0
    sparsity_scale: 1.
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      variance:
        lr: 0.001
  constant_steps: 5000
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.constant_steps}
    schedulers:
      - name: ConstantLR
        args:
          factor: 1.0
          total_iters: ${system.constant_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.constant_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  chunk_size: 2097152
  export_vertex_color: True

trainer:
  max_steps: 1e5
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 1e4 # 500
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
